import type { NewsStory } from "@/types/news-story";
import { stories as stories_2026_09_04 } from "./2026-09-04";
import { stories as stories_2026_08_31 } from "./2026-08-31";

export interface EditionMeta {
  /** Canonical key, also the /editions/[date] URL segment. */
  date: string;
  /** Human-readable range shown in the page header, e.g. "August 31 – September 1, 2026". */
  dateRangeLabel: string;
  stories: NewsStory[];
}

/**
 * All weekly editions, newest first. Index 0 is always the one shown at "/".
 * Regenerated by scripts/generate-real-edition.mjs each time a new edition
 * is created — do not hand-edit the entries array beyond adding a new one
 * the same way the script does, so this stays in sync with the files in
 * this directory.
 */
export const editions: EditionMeta[] = [
  { date: "2026-09-04", dateRangeLabel: "August 31, 2026 – September 2, 2026", stories: stories_2026_09_04 },
  { date: "2026-08-31", dateRangeLabel: "August 31 – September 1, 2026", stories: stories_2026_08_31 },
];

export const latestEdition = editions[0];

export function findEditionByDate(date: string): EditionMeta | undefined {
  return editions.find((edition) => edition.date === date);
}

export function findStoryById(id: string): NewsStory | undefined {
  for (const edition of editions) {
    const found = edition.stories.find((story) => story.id === id);
    if (found) return found;
  }
  return undefined;
}
