/**
 * Rewrites src/data/editions/index.ts to register a new edition, keeping
 * the registry in strict newest-first date order regardless of the order
 * editions were generated in — a backfilled/older edition must never
 * become editions[0]/latestEdition just because it was generated most
 * recently. Extracted from scripts/generate-real-edition.mjs so it can be
 * unit-tested against a scratch index.ts without running the real
 * GDELT/OpenAI/image pipeline (see scripts/test-editions-index.mjs).
 */

import fs from "node:fs";

const ENTRY_PATTERN = /\{ date: "([\d-]+)", dateRangeLabel: ("(?:[^"\\]|\\.)*"), stories: (\w+) \},/g;

/** YYYY-MM-DD strings sort correctly with a plain string comparison. */
function byDateDescending(a, b) {
  if (a.date < b.date) return 1;
  if (a.date > b.date) return -1;
  return 0;
}

export function updateEditionsIndex(editionsIndexPath, newEntry) {
  const existingText = fs.readFileSync(editionsIndexPath, "utf8");

  const existingEntries = [...existingText.matchAll(ENTRY_PATTERN)].map((m) => ({
    date: m[1],
    dateRangeLabelLiteral: m[2],
    varName: m[3],
  }));

  if (existingEntries.some((e) => e.date === newEntry.date)) {
    throw new Error(
      `Edition ${newEntry.date} is already present in editions/index.ts — this should have been caught earlier.`
    );
  }

  const newVarName = `stories_${newEntry.date.replace(/-/g, "_")}`;
  const allEntries = [
    { date: newEntry.date, dateRangeLabelLiteral: JSON.stringify(newEntry.dateRangeLabel), varName: newVarName },
    ...existingEntries,
  ];
  allEntries.sort(byDateDescending);

  const importLines = allEntries
    .map((e) => `import { stories as ${e.varName} } from "./${e.date}";`)
    .join("\n");
  const arrayLines = allEntries
    .map((e) => `  { date: "${e.date}", dateRangeLabel: ${e.dateRangeLabelLiteral}, stories: ${e.varName} },`)
    .join("\n");

  const fileContent = `import type { NewsStory } from "@/types/news-story";
${importLines}

export interface EditionMeta {
  /** Canonical key, also the /editions/[date] URL segment. */
  date: string;
  /** Human-readable range shown in the page header, e.g. "August 31 – September 1, 2026". */
  dateRangeLabel: string;
  stories: NewsStory[];
}

/**
 * All weekly editions, newest first. Index 0 is always the one shown at "/".
 * Regenerated by scripts/generate-real-edition.mjs each time a new edition
 * is created — do not hand-edit the entries array beyond adding a new one
 * the same way the script does, so this stays in sync with the files in
 * this directory.
 */
export const editions: EditionMeta[] = [
${arrayLines}
];

export const latestEdition = editions[0];

export function findEditionByDate(date: string): EditionMeta | undefined {
  return editions.find((edition) => edition.date === date);
}

export function findStoryById(id: string): NewsStory | undefined {
  for (const edition of editions) {
    const found = edition.stories.find((story) => story.id === id);
    if (found) return found;
  }
  return undefined;
}
`;

  fs.writeFileSync(editionsIndexPath, fileContent);
}
