/**
 * Reads and rewrites src/data/editions/index.ts, keeping the registry in
 * strict newest-first date order regardless of the order editions were
 * added/removed in — a backfilled/older edition must never become
 * editions[0]/latestEdition just because it was generated most recently,
 * and removing an old edition must never disturb the order of the ones
 * that remain. Extracted from scripts/generate-real-edition.mjs so it can
 * be unit-tested against a scratch index.ts without running the real
 * GDELT/OpenAI/image pipeline (see scripts/test-editions-index.mjs and
 * scripts/test-retention.mjs, which reuses parseExistingEntries()/
 * removeEditionsFromIndex() rather than re-implementing a second,
 * potentially-inconsistent parser/writer for this same file shape).
 */

import fs from "node:fs";

const ENTRY_PATTERN = /\{ date: "([\d-]+)", dateRangeLabel: ("(?:[^"\\]|\\.)*"), stories: (\w+) \},/g;

/** YYYY-MM-DD strings sort correctly with a plain string comparison. */
function byDateDescending(a, b) {
  if (a.date < b.date) return 1;
  if (a.date > b.date) return -1;
  return 0;
}

/** Parses the `editions` array entries out of an existing index.ts's text. */
export function parseExistingEntries(indexText) {
  return [...indexText.matchAll(ENTRY_PATTERN)].map((m) => ({
    date: m[1],
    dateRangeLabelLiteral: m[2],
    varName: m[3],
  }));
}

/** Renders a full index.ts file from a list of {date, dateRangeLabelLiteral, varName} entries. */
export function serializeIndexFile(allEntries) {
  const importLines = allEntries
    .map((e) => `import { stories as ${e.varName} } from "./${e.date}";`)
    .join("\n");
  const arrayLines = allEntries
    .map((e) => `  { date: "${e.date}", dateRangeLabel: ${e.dateRangeLabelLiteral}, stories: ${e.varName} },`)
    .join("\n");

  return `import type { NewsStory } from "@/types/news-story";
${importLines}

export interface EditionMeta {
  /** Canonical key, also the /editions/[date] URL segment. */
  date: string;
  /** Human-readable range shown in the page header, e.g. "August 31 – September 1, 2026". */
  dateRangeLabel: string;
  stories: NewsStory[];
}

/**
 * All weekly editions, newest first. Index 0 is always the one shown at "/".
 * Regenerated by scripts/generate-real-edition.mjs each time a new edition
 * is created — do not hand-edit the entries array beyond adding a new one
 * the same way the script does, so this stays in sync with the files in
 * this directory.
 */
export const editions: EditionMeta[] = [
${arrayLines}
];

export const latestEdition = editions[0];

export function findEditionByDate(date: string): EditionMeta | undefined {
  return editions.find((edition) => edition.date === date);
}

export function findStoryById(id: string): NewsStory | undefined {
  for (const edition of editions) {
    const found = edition.stories.find((story) => story.id === id);
    if (found) return found;
  }
  return undefined;
}
`;
}

function writeIndexFile(indexPath, allEntries) {
  fs.writeFileSync(indexPath, serializeIndexFile(allEntries));
}

export function updateEditionsIndex(editionsIndexPath, newEntry) {
  const existingText = fs.readFileSync(editionsIndexPath, "utf8");
  const existingEntries = parseExistingEntries(existingText);

  if (existingEntries.some((e) => e.date === newEntry.date)) {
    throw new Error(
      `Edition ${newEntry.date} is already present in editions/index.ts — this should have been caught earlier.`
    );
  }

  const newVarName = `stories_${newEntry.date.replace(/-/g, "_")}`;
  const allEntries = [
    { date: newEntry.date, dateRangeLabelLiteral: JSON.stringify(newEntry.dateRangeLabel), varName: newVarName },
    ...existingEntries,
  ];
  allEntries.sort(byDateDescending);

  writeIndexFile(editionsIndexPath, allEntries);
}

/**
 * Removes the entries for `datesToRemove` from index.ts, re-emitting the
 * file via the same serializeIndexFile() template updateEditionsIndex()
 * uses — never a second, divergent writer. Refuses (throws, writes
 * nothing) if the removal would leave the registry empty, as a second,
 * independent layer of the "never remove every edition" guarantee on top
 * of scripts/lib/retention.mjs's own plan-level check.
 */
export function removeEditionsFromIndex(editionsIndexPath, datesToRemove) {
  const existingText = fs.readFileSync(editionsIndexPath, "utf8");
  const existingEntries = parseExistingEntries(existingText);

  const removeSet = new Set(datesToRemove);
  const remaining = existingEntries.filter((e) => !removeSet.has(e.date));

  if (remaining.length === 0) {
    throw new Error("removeEditionsFromIndex: refusing to remove every entry from the registry.");
  }

  remaining.sort(byDateDescending);
  writeIndexFile(editionsIndexPath, remaining);

  return { removedCount: existingEntries.length - remaining.length, remainingDates: remaining.map((e) => e.date) };
}
